plugins {
    id "loom"
}

loom {
    clientOnlyMinecraftJar()
    accessWidenerPath = file("src/main/resources/optifabric.accesswidener")

    validateAccessWidener {
        enabled = false
    }
}

ploceus {
    clientOnlyMappings()
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings ploceus.featherMappings(feather_build)
    implementation parent
}
